logistic_regression:
  C: 0.5
  max_iter: 200

random_forest:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 2

xgboost:
  n_estimators: 100
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.8
